name: ci

#Run this workflow when a PR or a push to main occurs 
on:
  push:
    branches: 
      - "main"
  pull_request:


jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Files
        uses: actions/checkout@v4

      - name: Build image
        run: docker build -t api .

      - name: Run container
        run: |
          docker run -d --rm --name api -p 80:8080 -e PORT=8080 api

      - name: Test Container
        run:  curl --retry 3 --retry-delay 5 -fs http://localhost:80/

      - name: Test Apprentice Action
        uses: liatrio/github-actions/apprentice-action@master

      - name: Stop container
        if: always()
        run: docker stop api || true
